const dishesData = [
    // ===== ХОЛОДНЫЕ ЗАКУСКИ =====
    { name: 'Корзина домашнего хлеба', desc: 'деревенский, зерновой, пшеничный, льняной. ½ корзины — 4 половинки.', note: '1/2 корзины', allergens: false, spicy: false, section: 'cold' },
    { name: 'Пшеничная булочка с сыром и чесночным маслом', desc: 'булочка для бургера, сливочное масло с печёным чесноком, моцарелла.', note: 'отдача 7-8 мин', allergens: false, spicy: false, section: 'cold' },
    { name: 'Хачапури по-мегрельски / по-аджарски', desc: 'тесто: мука, молоко, дрожжи, масло, яйцо. Начинка: сулугуни, адыгейский сыр.', note: 'время 25 мин', allergens: false, spicy: false, section: 'cold' },
    { name: 'Фокачча', desc: 'основа римской пиццы, оливковое масло, розмарин.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Лахмаджун', desc: 'лепёшка пиде, начинка из баранины с томатами, луком, чесноком, чили, лимоном, кинзой.', note: 'без возможности убрать остроту', allergens: false, spicy: true, section: 'cold' },
    { name: 'Хумус (мезе)', desc: 'нут, оливковое масло, тахина, лук, чеснок, фундук, петрушка, копченая паприка, изюм, кедровый орех.', note: 'аллергены: фундук, кедровый орех', allergens: true, spicy: false, section: 'cold' },
    { name: 'Мухаммара (мезе)', desc: 'запечённый болгарский перец, багет, грецкий орех, чеснок, лимон, коричневый сахар, паприка, зира, шприца.', note: 'аллерген: грецкий орех', allergens: true, spicy: false, section: 'cold' },
    { name: 'Дзадзыки (мезе)', desc: 'йогурт, огурец, зелёный лук, укроп, петрушка, отварной желток, чеснок, оливковое масло.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Гуакомоле (мезе)', desc: 'авокадо, лайм, томат, красный лук, кинза, чили, чеснок, оливковое масло, зелёное масло.', note: 'содержит чили', allergens: false, spicy: true, section: 'cold' },
    { name: 'Римская пицца 4 сыра', desc: 'моцарелла, дорблю, камамбер с трюфелем, грана падано, сливочное масло. Соус белый (рикотта, сливки).', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Римская пицца с салями', desc: 'томатная основа, моцарелла, чорнозем, грана падано, сливочное масло.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Римская пицца с грушей и горгонзолой', desc: 'белый соус, моцарелла, груша, дорблю, грецкий орех, грана падано, руккола.', note: 'аллерген: грецкий орех', allergens: true, spicy: false, section: 'cold' },
    { name: 'Тарелка солений', desc: 'капуста квашеная, маринованный огурец, слабосолёные огурцы, острый перец, патиссоны, красный лук.', note: 'содержит острый перец', allergens: false, spicy: true, section: 'cold' },
    { name: 'Рулетики из баклажана', desc: 'начинка: грецкий орех, творожный сыр, хмели-сунели, кинза, чеснок, гранат, мёд.', note: 'аллергены: орех, мёд', allergens: true, spicy: false, section: 'cold' },
    { name: 'Маринованная сельдь с жареным картофелем', desc: 'филе Матиас, картофель стоун, красный маринованный лук, укроп, оливковое масло.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Вяленые колбасы и сыры', desc: 'грана падано, камамбер, горгонзола, фуэт, чоризо.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Карпаччо из томатов', desc: 'розовые томаты, бальзамический уксус, каперсы, оливки, зелёное масло, базилик.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Вителло тонато', desc: 'ростбиф, соус тонато (яйцо, горчица, тунец, каперсы, анчоусы, пармезан, бальзамик).', note: 'содержит горчицу', allergens: true, spicy: false, section: 'cold' },
    { name: 'Тартар из тунца', desc: 'тунец, красный лук, зелёный лук, чили, кинза, цитрусовая заправка, мусс из авокадо.', note: 'содержит чили', allergens: false, spicy: true, section: 'cold' },
    { name: 'Тартар из говядины', desc: 'вырезка, ворчестер, горчица зернистая и гладкая, красный лук, каперсы, пармезан.', note: 'содержит горчицу', allergens: true, spicy: false, section: 'cold' },
    { name: 'Тост с форелью', desc: 'хлеб, авокадо, яйцо, форель с/с, соус голландез, зелёное масло, семена льна.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Тост с томатами', desc: 'хлеб, томат, песто, моцарелла, руккола, кедровый орех, бальзамический крем.', note: 'аллерген: кедровый орех', allergens: true, spicy: false, section: 'cold' },
    { name: 'Драники из цукини с форелью', desc: 'драники (цукини, яйцо, мука, пармезан), гуакамоле, форель, красная икра, укроп.', note: '', allergens: false, spicy: false, section: 'cold' },
    { name: 'Паштет из куриных сердечек', desc: 'сердца, печень, сливки, чеснок, лук, белое вино. Луковый джем, фундук.', note: 'аллерген: фундук', allergens: true, spicy: false, section: 'cold' },
    { name: 'Хумус с цыпленком', desc: 'хумус, оливковое масло, паприка, орегано, кунжут. Цыпленок в панировке (мука, крахмал, чеснок).', note: '', allergens: false, spicy: false, section: 'cold' },

    // ===== ГОРЯЧИЕ ЗАКУСКИ =====
    { name: 'Гренки с сыром', desc: 'хлеб, чесночный край, грана подано, айоли из печёного чеснока.', note: '', allergens: false, spicy: false, section: 'hotstarter' },
    { name: 'Креветки в чесночном соусе', desc: 'креветки в соевом, розмарине, масле, обжарка со сливками, вином, чесноком, лимоном, чили.', note: 'содержит чили', allergens: false, spicy: true, section: 'hotstarter' },
    { name: 'Сыр в панировке', desc: 'моцарелла, пармезан, чеддер, яйцо, мука, панировка. Соус брусничный.', note: '', allergens: false, spicy: false, section: 'hotstarter' },
    { name: 'Острая курица с соусом блюд', desc: 'куриная грудка в панировке, острая смесь (сливочное масло, ширма, мёд, лайм, чеснок).', note: 'аллерген: мёд, острое', allergens: true, spicy: true, section: 'hotstarter' },
    { name: 'Форель с брокколи', desc: 'филе форели, брокколи, чеснок, куриный бульон, сливки, сулугуни, петрушка.', note: '', allergens: false, spicy: false, section: 'hotstarter' },
    { name: 'Курица с грибами', desc: 'куриное филе, шампиньоны, порей, чеснок, бульон, сливки, сулугуни.', note: '', allergens: false, spicy: false, section: 'hotstarter' },
    { name: 'Хрустящий салат с баклажанами', desc: 'баклажан, крахмал, томаты, рикотта, лимон, сумах, заправка (чили, соевый, лайм), семечки, кунжут.', note: 'содержит чили', allergens: false, spicy: true, section: 'hotstarter' },

    // ===== СУПЫ =====
    { name: 'Харчо', desc: 'говядина, кинза, лук, чеснок, чили, томаты, грецкий орех, ткемали, хмели-сунели, рис.', note: 'аллерген: грецкий орех, острое', allergens: true, spicy: true, section: 'soup' },
    { name: 'Карельская уха', desc: 'рыбный бульон, картофель, форель, судак, сливки, томаты, зелень.', note: '', allergens: false, spicy: false, section: 'soup' },
    { name: 'Куриный суп с домашней лапшой', desc: 'куриный бульон, пассировка (морковь, лук, сельдерей), куриные кельки, лапша, яйцо, перец.', note: 'может казаться острым из-за перца', allergens: false, spicy: false, section: 'soup' },
    { name: 'Том ям', desc: 'креветки, осьминоги, кальмар, кунжутное масло, порей, том ям паста, кокосовое молоко, чили, водоросли, рис.', note: 'острое', allergens: false, spicy: true, section: 'soup' },
    { name: 'Борщ с мраморной говядиной', desc: 'говяжий бульон, свекольный фреш, морковь, лук, чеснок, картофель, свекла, мраморная говядина. Со сметаной, смальцем, ржаным хлебом.', note: '', allergens: false, spicy: false, section: 'soup' },
    { name: 'Тыквенный крем-суп', desc: 'тыква, плавленый сыр, мускатный орех, семечки, шалфей, гренки. Можно добавить креветки.', note: '', allergens: false, spicy: false, section: 'soup' },

    // ===== ГОРЯЧИЕ БЛЮДА =====
    { name: 'Свиные рёбра с печёным картофелем', desc: 'рёбра в глазури Jack Daniels, картофель стоун, маринованный огурец, арахис, чили, кунжут.', note: 'аллергены: арахис, острое', allergens: true, spicy: true, section: 'main' },
    { name: 'Говяжий язык', desc: 'томлёный язык, соус демиглас, сливки, картофель, розмарин, чеснок, грибы, зелёный лук.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Форель с овощами в пергаменте', desc: 'форель, терияки, картофель, цветная капуста, брокколи, черри, шампиньоны, красный лук, кунжут.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Судак с цуккини', desc: 'судак, мука, тимьян, цуккини, дзадзыки, укроп, зелёное масло.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Соте из морепродуктов', desc: 'осьминоги, кальмары, креветки, судак, лук-порей, чеснок, белое вино, сливки, кокосовое молоко, гренки.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Томлёные говяжьи щёчки', desc: 'щёчки, куриный бульон, шоколад, клюква, пюре из цветной капусты, грана падано, сливочное масло.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Котлета из индейки', desc: 'фарш индейки, картофельное пюре, сливки, горчица, зелёный горошек.', note: 'содержит горчицу', allergens: true, spicy: false, section: 'main' },
    { name: 'Шипящая сковородка с овощами', desc: 'обжаренное мясо, лук, болгарский перец, картофель айдахо, кинза, чеснок.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Бургер куриный', desc: 'булочка, куриное филе в панировке, чеддер, ромейн, соус (майонез, горчица, кетчуп), огурец, острая смесь.', note: 'аллерген: горчица, острое', allergens: true, spicy: true, section: 'main' },
    { name: 'Бургер BBQ из мраморной говядины', desc: 'булочка, котлета с сыром и беконом, томаты, соус BBQ. Прожарка Medium/Well Done.', note: 'предложить соус и картофель', allergens: false, spicy: false, section: 'main' },
    { name: 'Бургер с рваной свининой', desc: 'мясо свиных рёбер в глазури, чеддар, маринованные огурцы, салат коул слоу, соус BBQ.', note: 'предложить соус и картофель', allergens: false, spicy: false, section: 'main' },
    { name: 'Паста с морепродуктами', desc: 'домашняя лапша, чеснок, чили, кальмар, креветки, осьминог, черри, белое вино, томаты, сливки, пармезан.', note: 'острое', allergens: false, spicy: true, section: 'main' },
    { name: 'Паста с песто', desc: 'спагетти, песто (базилик, кедровый орех, пармезан), черри, моцарелла, руккола.', note: 'аллерген: кедровый орех', allergens: true, spicy: false, section: 'main' },
    { name: 'Карбонара', desc: 'спагетти, бекон, лук, чеснок, сливки, яйцо, пармезан.', note: '', allergens: false, spicy: false, section: 'main' },
    { name: 'Паста с томлёными говяжьими щёчками', desc: 'рожки, чеснок, лук, щёчки, куриный бульон, грана падано.', note: '', allergens: false, spicy: false, section: 'main' },

    // ===== ГРИЛЬ =====
    { name: 'Скумбрия', desc: 'маринованная в оливковом масле, тимьяне, лимон, салат-микс, чимичурри.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Кёфте из говядины', desc: 'фарш люля (говядина, лук, хмели-сунели, сумах, зира, чеснок), соус, красный лук, фокачча.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Кёфте из ягнёнка', desc: 'фарш баранины, лук, чеснок, хмели-сунели, сумах, зира, соус, красный лук, фокачча.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Шашлык из курицы', desc: 'филе бедра, лимон, паприка, чеснок, газированная вода. Соус, красный лук, фокачча.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Шашлык из свинины', desc: 'свиная шея, хмели-сунели, горчица, газированная вода. Соус, красный лук, фокачча.', note: 'содержит горчицу', allergens: true, spicy: false, section: 'grill' },
    { name: 'Филе миньон', desc: 'говяжье филе, сливочное масло с чесноком и зеленью, чимичурри, салат-микс.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Стейк Нью-Йорк', desc: 'тонкий край спинной части, масло с чесноком и зеленью, чимичурри, салат-микс.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Стейк Рибай', desc: 'толстый край спинной части, сливочное масло, чимичурри, салат-микс.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: '½ Цыпленка', desc: 'половинка цыплёнка в маринаде, шашлычный соус, микс зелени.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Стейк Форели', desc: 'форель, соль, перец, салат-микс, чимичурри, лимон.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Морепродукты на гриле', desc: 'креветки, кальмар, салат-микс, чимичурри, лимон.', note: '', allergens: false, spicy: false, section: 'grill' },
    { name: 'Баклажаны с говядиной на гриле', desc: 'баклажан, фарш говяжий, хмели-сунели, сулугуни, красный лук, фокачча, шашлычный соус.', note: '', allergens: false, spicy: false, section: 'grill' },

    // ===== ГАРНИРЫ =====
    { name: 'Томаты с ялтинским луком', desc: 'томаты, красный лук, кинза, соль, перец.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Кукуруза', desc: 'кукуруза, сливочное масло, чили, чеснок, петрушка.', note: 'острое', allergens: false, spicy: true, section: 'side' },
    { name: 'Овощи на гриле', desc: 'шампиньоны, перец, кабачок, баклажан, томат, оливковое масло, чеснок, соевый соус.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Картофель по-деревенски', desc: 'картофель стоун, чеснок, петрушка, соль, перец.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Батат фри', desc: 'батат, соль, перец.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Тако', desc: 'ромейн, тунец, цитрусовая заправка, кунжут, мусс из авокадо, ананасовая сальса, лук фри.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Деревенский салат', desc: 'томат, огурец, редис, укроп, соль, перец.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Судак на пару', desc: 'судак, цукини в маринаде, дзадзыки, зелёное масло.', note: '', allergens: false, spicy: false, section: 'side' },
    { name: 'Куриная грудка на гриле', desc: 'куриная грудка, брокколи, томат, авокадо, зелёное масло.', note: '', allergens: false, spicy: false, section: 'side' },

    // ===== ДЕСЕРТЫ =====
    { name: 'Медовик', desc: 'медовик с клубникой, сахарная пудра, мята.', note: '', allergens: false, spicy: false, section: 'dessert' },
    { name: 'Брауни с вишней', desc: 'брауни (шоколад, масло), мороженое, шоколадный ганаш, малина.', note: '', allergens: false, spicy: false, section: 'dessert' },
    { name: 'Чизкейк', desc: 'творожный сыр, яйцо, сливки, ганаш, мята.', note: '', allergens: false, spicy: false, section: 'dessert' },
    { name: 'Наполеон', desc: 'слоёное тесто, крем шантипак, малина, мята.', note: '', allergens: false, spicy: false, section: 'dessert' },
    { name: 'Яблочный штрудель', desc: 'слоёное тесто, яблоки, корица, изюм, грецкий орех, мороженое.', note: 'аллерген: грецкий орех', allergens: true, spicy: false, section: 'dessert' },
    { name: 'Мороженое / сорбет', desc: 'клубника, шоколад, ваниль, сорбет чёрная смородина, сорбет лайм/лимон.', note: '', allergens: false, spicy: false, section: 'dessert' },
    { name: 'Блинчики', desc: '3 шт. со сметаной, черничным вареньем или сгущённым молоком.', note: '', allergens: false, spicy: false, section: 'dessert' },
    { name: 'Сырники', desc: '2 шт. со сметаной, черничным вареньем или сгущённым молоком.', note: '', allergens: false, spicy: false, section: 'dessert' },

    // ===== СОУСЫ =====
    { name: 'Соус Барбекю', desc: 'лук, лимон, горчица, кетчуп, ворчестер, соевый, паприка, сахар, яблоки, жидкий дым.', note: 'содержит горчицу', allergens: true, spicy: false, section: 'sauce' },
    { name: 'Блючиз', desc: 'соус айоли, сыр блючиз, смесь перцев, шрирача.', note: 'острое', allergens: false, spicy: true, section: 'sauce' },
    { name: 'Чимичурри', desc: 'лук, чеснок, кинза, петрушка, уксус, лайм, чили, оливковое масло.', note: 'острое', allergens: false, spicy: true, section: 'sauce' },
    { name: 'Чипотле', desc: 'айоли, перец чипотле.', note: 'острое', allergens: false, spicy: true, section: 'sauce' },
    { name: 'Шашлычный соус', desc: 'томаты, чеснок, кинза, петрушка, чили, соль, перец, сахар.', note: 'острое', allergens: false, spicy: true, section: 'sauce' }
];
